name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_native_splash: ^2.2.19
  provider: ^6.0.5
  http: ^0.13.5
  intl: 0.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  permission_handler: ^10.2.0
  flutter_local_notifications: ^14.0.0
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+4
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_analytics: ^10.2.1
  firebase_crashlytics: ^3.3.0
  device_preview: ^1.1.0

  # Widget
  flutter_zoom_drawer: ^3.0.4+1
  table_calendar: ^3.0.8
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  fluttertoast: ^8.2.1
  loading_animation_widget: ^1.2.0+4
  readmore: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  source_gen: ^1.2.7
  build_runner: ^2.3.3
  flutter_gen: ^5.3.0
  flutter_gen_runner: ^5.3.0
  hive_generator: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schyler-Regular.ttf
        - asset: fonts/Schyler-Italic.ttf
          style: italic

# flutter_launcher_icons
flutter_icons:
  image_path: assets/app_icon.png
  android: true
  ios: true
  adaptive_icon_foreground: assets/app_icon.png
  adaptive_icon_background: '#ffffff'

# flutter_native_splash
flutter_native_splash:
  image: assets/splash_screen.png
  color: '#ffffff'
  icon_background_color: '#ffffff'
  android: true
  ios: true
  web: false
  android_12:
    image: assets/splash_screen.png
    color: '#ffffff'
    icon_background_color: '#ffffff'

# flutter_gen
flutter_gen:
  output: lib/res/generated/asset
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors.xml
    outputs:
      class_name: Palette

# intl
flutter_intl:
  enabled: true
  arb_dir: lib/res/l10n
  output_dir: lib/res/generated/l10n